# Docker Compose for local development
# Note: Every names need to be different and used accordingly

version: "3.9"

services:
  database:
    image: postgres:alpine
    container_name: remix-turborepo-database
    hostname: database
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

volumes:
  postgres:
    name: remix-turborepo-postgres
